services:
  note-api:
    image: note-api
    depends_on:
      - postgres
      - redis
    environment:
      WAIT_HOSTS: postgres:5432, redis:6379
    ports:   
      - "8080:8080"
    build:
      context: .
      dockerfile: NoteApi/Dockerfile
    links:
      - redis  

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: notes_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - "5432:5432"
    volumes:
        - ./db/data:/var/lib/postgresql/data
        - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
        
  client:
    image: vue-client
    container_name: vue-client
    build: ../client
    ports:
      - "8082:8082"
    volumes:
    - /vue-client:/var/www/html/app

  proxy:
    image: proxy
    container_name: proxy
    build: ../Nginx
    ports:
      - "443:443"
    depends_on:
      - client
      - note-api
    restart: always    